(
("xl" "{concept \"XL\"}")
("cp" "{concept \"cp\" \"Concept Programming\"}")
("complexity" "{concept \"complexity\"}")
("concept" "{concept \"concept\"}")
("concepts" "{concept \"concept\" \"concepts\"}")
("representation" "{concept \"representations\" \"representation\"}")
("representations" "{concept \"representations\"}")
("represents" "{concept \"representations\" \"represents\"}")
("represent" "{concept \"representations\" \"represent\"}")
("represented" "{concept \"representations\" \"represented\"}")
("pb" "{concept \"problem\" \"problem space\"}")
("problem" "{concept \"problem\"}")
("problems" "{concept \"problem\" \"problems\"}")
("cs" "{concept \"code\" \"code space\"}")
("code" "{concept \"code\"}")
("objects" "{concept \"objects\"}")
("object" "{concept \"objects\" \"object\"}")
("metric" "{concept \"metrics\" \"metric\"}")
("metrics" "{concept \"metrics\"}")
("ccast" "{concept \"concept-cast\" \"concept cast\"}")
("synnoise" "{concept \"synnoise\" \"syntactic noise\"}")
("semnoise" "{concept \"semnoise\" \"semantic noise\"}")
("bandwidth" "{concept \"bandwidth\"}")
("signoise" "{concept \"signoise\" \"signal/noise ratio\"}")
("syntax" "{concept \"syntax\"}")
("semantics" "{concept \"semantics\"}")
("mozart" "<A href=\"http://mozart-dev.sf.net\">Mozart</A>")
("ada" "{wiki \"Ada_programming_language\" \"Ada\"}")
("c" "{wiki \"C_programming_language\" \"C\"}")
("c++" "{wiki \"C_plus_plus\" \"C++\"}")
("python" "{wiki \"Python_programming_language\" \"Python\"}")
("xml" "{wiki \"XML\" \"XML\"}")
("java" "{wiki \"Java_programming_language\" \"Java\"}")
("lisp" "{wiki \"Lisp_programming_language\" \"Lisp\"}")
("smalltalk" "{wiki \"Smalltalk\" \"Smalltalk\"}")
("prolog" "{wiki \"Prolog_programming_language\" \"Prolog\"}")
("pascal" "{wiki \"Pascal_programming_language\" \"Pascal\"}")
("apl" "{wiki \"APL_programming_language\" \"APL\"}")
("basic" "{wiki \"BASIC_programming_language\" \"BASIC\"}")
("c#" "{wiki \"C_sharp\" \"C#\"}")
("eiffel" "{wiki \"Eiffel_programming_language\" \"Eiffel\"}")
("gui" "{wiki \"GUI\" \"GUI\"}")
("stl" "{wiki \"Standard_template_library\" \"C++ STL\"}")
("generic" "{concept \"generics\" \"generic\"}")
("generics" "{concept \"generics\"}")
)
