<P><B>Quick Links</B><BR>
{concept "toplevel" "Home"}<br>
<A href="{blogToplevel}index.html">News</A><br>
{inside "status" "Status"}<br>
{inside "build" "Building XL"}<br>
<A href="http://lists.sourceforge.net/lists/listinfo/mozart-dev-lx-lang">XL Mailing List</A>

<P><B>Understanding XL</B><BR>
{concept "top" "Conceptual overview"}<br>
{example "top" "XL examples"}<br>
{inside "top" "Inside XL"}<br>

<P><B>In depth</B><BR>
<A href="http://svn.sourceforge.net/viewcvs.cgi/xlr/trunk/xl2/">Browse SVN</A><br>
<A href="http://xlr.cvs.sourceforge.net/xlr/xl2/">Browse CVS (deprecated)</A><br>
<A href="http://sourceforge.net/projects/xlr">SourceForge Info</A><br>
<A href="mailto:{email}">Contact</A><br>

<P><B>Other projects</B><BR>
<A href="http://www.gnu.org">GNU Project</A><br>
<A href="http://mozart-dev.sf.net/">The Mozart Project</A><br>

<table height="900px">
<tr><td></tr></td>
</table>
