#******************************************************************************
#  Christophe de Dinechin                                      XROMA PROJECT
#  XROMA: Makefile.config
#******************************************************************************
#
#  File Description:
#
#    This is the shared makefile configuration and shared targets for all
#    Mozart directories
#
#
#
#
#
#
#******************************************************************************
#This document is distributed under the Xroma public license.
#See the accompanying license file for information.
#******************************************************************************
#* File       : $RCSFile$
#* Revision   : $Revision$
#* Date       : $Date$
#******************************************************************************

DEFINES_debug=-DDEBUG -DMZ_DEBUG=1
DEFINES_opt=-DNDEBUG
LDFLAGS_debug=-g
TPP=$(BROOT)tpp/tone_preprocessor

include $(BROOT)Makefile.config.$(BUILDENV)

