#!/bin/bash
#******************************************************************************
#  Christophe de Dinechin                                          XL PROJECT
#  XL COMPILER TESTS: alltests
#******************************************************************************
#
#  File Description:
#
#    Script for testing the compiler
#
#    This file runs through every possible test. It looks for all files
#    ending in .test below the current directory, and executes them.
#
#
#
#
#
#******************************************************************************
#This document is distributed under the GNU General Public License
#See the enclosed COPYING file or http://www.gnu.org for information
#******************************************************************************
#* File       : $RCSFile$
#* Revision   : $Revision$
#* Date       : $Date$
#******************************************************************************

# Environment - Note that 'xl' is typically a symbolic link to real compiler
TESTDIR=$(pwd)
XL=./nxl
SUCCESS=$TESTDIR/success.out
FAILURE=$TESTDIR/failure.out
PASS="pass"
ONE_FAILED=
PATTERN='[A-Za-z]*'
UPDATE=
NOCACHE=
if [ "$1" == '-c++' ]; then NOCACHE=1; shift; fi
if [ "$1" == "-update" -o "$1" == "-u" ]; then
   shift; UPDATE='*'$1'*'; PATTERN="$UPDATE"; shift;
fi
if [ ! -z "$1" ]; then PATTERN='*'"$1"'*'; shift; fi

export TESTDIR XL SUCCESS FAILURE PASS UPDATE

# Make sure the proper files are linked in place
ln -sf ../xl.bytecode .
ln -sf ../xl.syntax .
ln -sf ../xl_lib.h .
ln -sf ../xl_builtins.xs .
ln -sf ../*.stylesheet .
ln -sf ../nxl .

# Cleanup the test results
echo Tests successfully run on $(date) on $HOSTNAME > $SUCCESS
echo Failed tests on $(date) on $HOSTNAME > $FAILURE
rm -rf $TESTDIR/.xl

export XL

# Look for all possible tests in the test directory
for TEST in $(find $TESTDIR -name "$PATTERN".xl -print)
do
    TESTNAME=${TEST/$TESTDIR\/}
    echo -n Test: $TESTNAME...

    # Setup useful variables - These can be set in the test files
    BASE=${TESTNAME/\.xl}       # Basename
    REF=$BASE.ref               # Reference file
    LOG=$BASE.log               # Log file
    CMD=                        # Command to execute
    EXIT=0                      # Expected exit code (EXIT=2 for errors)
    RUN=                        # What to run afterwards
    COMPILE=                    # Compile command
    OPT=                        # XL compiler options
    INC="-I $(dirname $TEST)"   # XL include directory
    CACHED=

    # Extract interesting variables from the test
    eval $(./alltests.awk $TESTNAME)

    # Defaults if not set by the test
    if [ -z "$CMD" ]; then
        CMD="$XL $INC $OPT $TESTNAME";
        [ -z "$COMPILE" ] && { COMPILE="c++ -I. $BASE.cpp"; }
        [ -z "$RUN" ] && { RUN="./a.out"; }
    fi

    # Run the XL compiler on the test
    THIS_FAILED=
    ( $CMD ) > $LOG 2>&1
    RC=$?

    # Try to compile the resulting C++ unless script specifies otherwise
    if [ $EXIT -eq 0 ]; then
        if [ $RC -eq 0 ]; then
            # If we have a cached version, check if it stayed identical
            # If so, we can skip 'compile' and 'run', unless forced
            if [ -z "$NOCACHE" ]; then
                if [ -f "$BASE.cpp" ]; then
                    if diff -q $LOG $BASE.cpp > /dev/null 2>&1; then
                        # In that case, use the reference, don't run
                        echo > $LOG
                        cp $REF $LOG
                        RUN=
                        COMPILE=
                        CACHED="(Cached)"
                    fi
                fi
            fi

            # Compile the C++ code if needed
            if [ ! -z "$COMPILE" ]; then
                echo -n Compile...
                rm -f ./a.out
                mv -f $LOG $BASE.cpp
                $COMPILE > $LOG 2>&1
                RC=$?
            fi

            # Run the target if needed
            if [ $RC -eq 0 ]; then
                if [ ! -z "$RUN" ]; then
                    $RUN > $LOG 2>&1
                    RC=$?
                fi
            fi
        fi
    fi

    # Analyze the results
    if [ $RC -ne $EXIT ]; then
        THIS_FAILED="Exit code $RC, expected $EXIT"
    elif [ ! -z "$REF" ]; then
        sed 's@'$TESTDIR'@TESTS@g' < $LOG > $LOG.tmp && mv $LOG.tmp $LOG
        if diff -q $REF $LOG > /dev/null 2>&1; then
            THIS=ok
        elif [ ! -z "$UPDATE" ]; then
            echo "Updating reference for " $BASE
            mv -f $REF $REF.old
            cp $LOG $REF
        elif [ -f $REF ]; then
            THIS_FAILED="Output mismatch"
            diff $REF $LOG > $LOG.diff
            mv $LOG.diff $LOG
            rm -f $BASE.cpp
        else
            THIS_FAILED="Missing reference"
        fi
    elif [ ! -z "$GREP" ]; then
        if $GREP $LOG; then
            THIS=ok
        else
            THIS_FAILED="No pattern match"
        fi
    fi

    if [ -z "$THIS_FAILED" ]; then
        echo $TEST >> $SUCCESS
        if [ "$RC" -ne "0" ] ; then
            echo Success - negative test;
        else
            echo Success $CACHED;
        fi
        rm -f $LOG
    else
        echo $TEST:  $THIS_FAILED >> $FAILURE
        cat $LOG >> $FAILURE
        echo '*** FAILURE ***'
        ONE_FAILED=1
    fi
    rm -f ./a.out
done

if [ "$ONE_FAILED" ]; then echo; echo '*** FAILURES: ***' ; cat $FAILURE; fi
