# ******************************************************************************
# Makefile                                                            XL project
# ******************************************************************************
#
# File description:
#
#    Makefile for the native library for XL
#
#
#
#
#
#
#
#
# ******************************************************************************
# This software is licensed under the GNU General Public License v3
# (C) 2021, Christophe de Dinechin <christophe@dinechin.org>
# ******************************************************************************
# This file is part of XL
#
# XL is free software: you can r redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# XL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with XL, in a file named COPYING.
# If not, see <https://www.gnu.org/licenses/>.
# ******************************************************************************

# For pkg-config generation
PACKAGE_NAME=xl
PACKAGE_VERSION=0.0.1
PACKAGE_DESCRIPTION=An extensible programming language
PACKAGE_URL="http://github.com/c3d/xl"
PACKAGE_REQUIRES=

WARE.share=$(wildcard lib/*.xs lib/*.xl)
MIQ=../make-it-quick/
include $(MIQ)rules.mk
