#******************************************************************************
#  Christophe de Dinechin                                          XL PROJECT  
#  XL COMPILER / TESTS: Makefile
#******************************************************************************
#
#  File Description:
#
#    Makefile for testing the compiler
#
#    This file is here simply for convenience, to enable testing using the
#    make command.
#
#
#
#
#
#******************************************************************************
#This document is distributed under the GNU General Public License
#See the enclosed COPYING file or http://www.gnu.org for information
#******************************************************************************
#* File       : $RCSFile$
#* Revision   : $Revision$
#* Date       : $Date$
#******************************************************************************

all_tests: ALWAYS
	./alltests

ALWAYS:
