#!/bin/bash

BASE=${1/.tbl/}
MODULE=$(basename $BASE)
echo '#include "runtime.h"'
echo '#include "'$MODULE'_module.h"'
echo '#include "opcodes.h"'
[ -f $BASE'.cpp' ] && echo '#include "'$MODULE'.cpp"'
echo 'XL_BEGIN'
echo '#include "'$MODULE'.tbl"'
echo 'XL_END'
