#!/bin/bash

echo '#include "runtime.h"'
echo '#include "'$1'_module.h"'
echo '#include "opcodes.h"'
[ -f $1'.cpp' ] && echo '#include "'$1'.cpp"'
echo 'ELFE_BEGIN'
echo '#include "'$1'.tbl"'
echo 'ELFE_END'
