#******************************************************************************
#  Christophe de Dinechin                                      ELFE PROJECT
#  Makefile.config
#******************************************************************************
#
#  File Description:
#
#    This is the shared makefile configuration and shared targets for all
#    Mozart directories
#
#
#
#
#
#
#******************************************************************************
# This program is released under the GNU General Public License.
# See http://www.gnu.org/copyleft/gpl.html for details
#******************************************************************************
#* File       : $RCSFile$
#* Revision   : $Revision$
#* Date       : $Date$
#******************************************************************************

DEFINES_debug=-DDEBUG
DEFINES_opt=-DNDEBUG
LDFLAGS_debug=-g

ifndef BUILDENV
BUILDENV=auto
endif

include $(BROOT)Makefile.config.$(BUILDENV)

