name: Continuous integration for XL

on: [push]

jobs:
  build:
    name: Test ${{ matrix.variant }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        variant: [debug, opt, release]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: apt-get install for ${{ matrix.variant }} on ${{ matrix.os }}
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install -y llvm-dev git gcc g++ make findutils gawk
    - name: Brew install for ${{ matrix.variant }} on ${{ matrix.os }}
      if: startsWith(matrix.os, 'macOS')
      run: brew install llvm
    - name: make check for ${{ matrix.variant }} on ${{ matrix.os }}
      run:  PATH=$PATH:/usr/local/opt/llvm/bin make ${{ matrix.variant }}-check
